name: Make my personal site fly 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Github Package Registry
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build Docker Image
        run: docker build -t main:latest .
        
      - name: Push Image to Registry
        run: docker push main:latest
